console_title_template = '{{ .Shell }} in {{ .Folder }}'
version = 3

[palette]
  base = '#191724'
  docker = 'p:foam'
  false = 'p:love'
  foam = '#9ccfd8'
  git = 'p:iris'
  go = 'p:rose'
  gold = '#f6c177'
  haskell = 'p:rose'
  highlight-high = '#524f67'
  highlight-low = '#21202e'
  highlight-med = '#403d52'
  iris = '#c4a7e7'
  julia = 'p:rose'
  love = '#eb6f92'
  lua = 'p:rose'
  muted = '#6e6a86'
  os-bg = 'p:transparent'
  os-fg = 'p:foam'
  overlay = '#26233a'
  path = 'p:gold'
  pine = '#31748f'
  python = 'p:rose'
  root-bg = 'p:gold'
  root-fg = 'p:base'
  rose = '#ebbcba'
  rust = 'p:rose'
  subtle = '#908caa'
  surface = '#1f1d2e'
  text = '#e0def4'
  time = 'p:muted'
  true = 'p:pine'

[transient_prompt]
  template = '{{ now | date "15:04:05" }} {{ if gt .Code 0 }}<p:false>❯</>{{ else }}<p:true>❯</>{{ end }} '
  foreground = 'p:time'

[upgrade]
  source = 'cdn'
  interval = '168h'
  auto = false
  notice = false

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    template = ' {{ .Icon }} '
    foreground = 'p:os-fg'
    background = 'p:os-bg'
    type = 'os'
    style = 'plain'
    foreground_templates = ['{{ if .Root }}p:root-fg{{ end }}']
    background_templates = ['{{ if .Root }}p:root-bg{{ end }}']

    [blocks.segments.properties]
      cache_duration = 'none'
      windows = ''

  [[blocks.segments]]
    template = ' {{ .Path }} '
    foreground = 'p:path'
    type = 'path'
    style = 'plain'

    [blocks.segments.properties]
      cache_duration = 'none'
      folder_icon = '..'
      home_icon = '~'
      style = 'agnoster_short'

  [[blocks.segments]]
    template = '{{ .HEAD }}{{ if (.Working.Changed) }} {{ end }}{{ if (.Staging.Changed) }} {{ end }}{{if gt .Behind 0}} ⇣{{ end }}{{ if gt .Ahead 0 }} ⇡{{ end }} '
    foreground = 'p:git'
    type = 'git'
    style = 'plain'

    [blocks.segments.properties]
      branch_icon = ' '
      cache_duration = 'none'
      cherry_pick_icon = ' '
      commit_icon = ' '
      fetch_stash_count = false
      fetch_status = true
      fetch_upstream_icon = false
      merge_icon = ' '
      no_commits_icon = ' '
      rebase_icon = ' '
      revert_icon = ' '
      tag_icon = ' '

  [[blocks.segments]]
    template = ' {{ .Context }} '
    foreground = 'p:docker'
    type = 'docker'
    style = 'plain'

    [blocks.segments.properties]
      cache_duration = 'none'

  [[blocks.segments]]
    template = ' {{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }} '
    foreground = 'p:go'
    type = 'go'
    style = 'plain'

    [blocks.segments.properties]
      cache_duration = 'none'

  [[blocks.segments]]
    template = ' {{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }} '
    foreground = 'p:haskell'
    type = 'haskell'
    style = 'plain'

    [blocks.segments.properties]
      cache_duration = 'none'

  [[blocks.segments]]
    template = ' {{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }} '
    foreground = 'p:julia'
    type = 'julia'
    style = 'plain'

    [blocks.segments.properties]
      cache_duration = 'none'

  [[blocks.segments]]
    template = ' {{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }} '
    foreground = 'p:lua'
    type = 'lua'
    style = 'plain'

    [blocks.segments.properties]
      cache_duration = 'none'

  [[blocks.segments]]
    template = ' {{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }} '
    foreground = 'p:python'
    type = 'python'
    style = 'plain'

    [blocks.segments.properties]
      cache_duration = 'none'
      display_default = false
      display_mode = 'context'

  [[blocks.segments]]
    template = ' {{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }} '
    foreground = 'p:rust'
    type = 'rust'
    style = 'plain'

    [blocks.segments.properties]
      cache_duration = 'none'

  [[blocks.segments]]
    template = '󰔟 {{ .FormattedMs }} '
    foreground = 'p:true'
    type = 'executiontime'
    style = 'plain'
    foreground_templates = ['{{ if .Code }}p:false{{ end }}']

    [blocks.segments.properties]
      cache_duration = 'none'
      style = 'austin'
      threshold = 500.0

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    template = '❯ '
    foreground = 'p:true'
    type = 'status'
    style = 'plain'
    foreground_templates = ['{{ if gt .Code 0 }}p:false{{ end }}']

    [blocks.segments.properties]
      always_enabled = true
      cache_duration = 'none'
